export default {
  login: "Deep-dsd",
  id: 78144390,
  node_id: "MDQ6VXNlcjc4MTQ0Mzkw",
  avatar_url: "https://avatars.githubusercontent.com/u/78144390?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/Deep-dsd",
  html_url: "https://github.com/Deep-dsd",
  followers_url: "https://api.github.com/users/Deep-dsd/followers",
  following_url: "https://api.github.com/users/Deep-dsd/following{/other_user}",
  gists_url: "https://api.github.com/users/Deep-dsd/gists{/gist_id}",
  starred_url: "https://api.github.com/users/Deep-dsd/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/Deep-dsd/subscriptions",
  organizations_url: "https://api.github.com/users/Deep-dsd/orgs",
  repos_url: "https://api.github.com/users/Deep-dsd/repos",
  events_url: "https://api.github.com/users/Deep-dsd/events{/privacy}",
  received_events_url: "https://api.github.com/users/Deep-dsd/received_events",
  type: "User",
  site_admin: false,
  name: "Deep Sankar De",
  company: null,
  blog: "https://deepsde.netlify.app/",
  location: "India",
  email: null,
  hireable: null,
  bio: "May the force be with you",
  twitter_username: null,
  public_repos: 22,
  public_gists: 0,
  followers: 0,
  following: 0,
  created_at: "2021-01-28T09:44:56Z",
  updated_at: "2024-02-08T16:56:49Z",
};
